spring:
  application:
    name: eureka-service-registry
  boot:
    admin:
      #Spring Boot Admin Page is accessible on "/sba/dashboard".
      context-path: /sba/dashboard
  ## Spring Cloud Config configuration
  config:
    import: "optional:configserver:http://config-server.kvhome.in"

## Server Port
server:
  port: 8761

## Eureka Server Configs
eureka:
  datacenter: i7-2700-kube-cluster
  instance:
#    hostname: localhost
    hostname: service-registry.kvhome.in
    instanceId: client-${random.uuid}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    # Commented out fetch-registry property as it causes issue with SpringBootAdmin integration.
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/